version: "3.8"
services:
  backend:
    build: .
    container_name: "flask-mongodb-backend"
    environment:
      FLASK_DEBUG: ${FLASK_DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_SERVER: ${REDIS_SERVER}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_SERVER_PORT: ${MAIL_SERVER_PORT}
      DEFAULT_MAIL_SENDER_ADDRESS: ${DEFAULT_MAIL_SENDER_ADDRESS}
      ADMIN_MAIL_ADDRESSES: ${ADMIN_MAIL_ADDRESSES}
      DEFAULT_MAIL_SENDER_PASSWORD: ${DEFAULT_MAIL_SENDER_PASSWORD}
    command: ./gunicorn_starter.sh
    ports:
      - "5000:5000"
    networks:
      - flask_service
    depends_on:
      backend_db:
        condition: service_healthy
      redis:
          condition: service_healthy

  backend_db:
    image: mongo:latest
    container_name: "mongodb-database"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - $PWD/.dbdata:/data/db
    ports:
      - "27018:27017"
    networks:
      - flask_service
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet

  redis:
    image: redis:6.2.6-alpine
    container_name: "redis-server"
    command: redis-server --requirepass admin
    ports:
      - "6378:6379"
    networks:
      - flask_service
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]

networks:
  flask_service:
    name: flask_network
